spring:
  application:
    name: service-provider-api
  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    platform: postgre
    url: jdbc:postgresql://postgres_sch:5432/postgres
    username: admin
    password: password
    testWhileIdle: true
    validationQuery: SELECT 1
    continue-on-error: true
server:
  port: 8086