spring:
  application:
    name: service-provider-api
  jpa:
    open-in-view: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgre
    url: jdbc:postgresql://schdb.cximbrleqgzo.us-east-2.rds.amazonaws.com:5432/postgres
    username: sch_admin
    password: 1234work

server:
  port: 5000